# our rewrite function
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rewriter
spec:
  template:
    spec:
      containers:
        - image: pilhuhn/rewrite-funq-native
          env:
            - name: RULES
              value: |
                  key3: .ce.source
                  key1: $key1 + .ce.id
                  -key2
          imagePullPolicy: Always
